# Numpy Tutorial

This notebook is basically a Jupyter Notebook version of the below tutorial pages.

* https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
* https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

In [3]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

In [7]:
a.itemsize

8

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [11]:
type(b)

numpy.ndarray

# Array Creation

In [12]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [13]:
a.dtype

dtype('int64')

In [14]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [19]:
c = np.array([[1,2],[3,4]], dtype=complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [23]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [25]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [29]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [33]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [34]:
np.arange(0, 2, 0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [35]:
from numpy import pi
np.linspace( 0, 2, 9 )

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [37]:
x = np.linspace( 0, 2*pi, 100 )

In [39]:
f = np.sin(x)

# Broadcasting

In [43]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([ 2.,  4.,  6.])

In [42]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([ 2.,  4.,  6.])

## General Broadcasting Rule

Two dimensions are compatible when

* they are **equal**, or
* one of them is **1**

In [56]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

In [54]:
x

array([0, 1, 2, 3])

In [57]:
y

array([ 1.,  1.,  1.,  1.,  1.])

In [58]:
x.shape

(4,)

In [47]:
y.shape

(5,)

In [48]:
x + y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [50]:
xx.shape

(4, 1)

In [51]:
xx + y

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.]])

In [59]:
(x + z).shape

(3, 4)

In [60]:
x + z

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.]])

In [61]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b


array([[  1.,   2.,   3.],
       [ 11.,  12.,  13.],
       [ 21.,  22.,  23.],
       [ 31.,  32.,  33.]])

## Future Reference
* http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc